# Generated by Django 3.2.3 on 2021-06-04 00:15

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models
import votes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CamaraVoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Inicio')),
                ('termino', models.DateTimeField(verbose_name='Termino')),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('imagem', stdimage.models.StdImageField(default='/static/img/blank-profile.png', upload_to=votes.models.get_file_path, verbose_name='Imagem')),
                ('camara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.camaravoto')),
            ],
        ),
        migrations.AddField(
            model_name='camaravoto',
            name='tempo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='votes.tempo', verbose_name='Tempo'),
        ),
    ]
