# Generated by Django 3.2.3 on 2021-06-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20210604_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='camaravoto',
            name='slug',
            field=models.SlugField(blank=True, editable=False, verbose_name='Slug'),
        ),
    ]
